power<-read.csv2("household_power_consumption.txt", header=TRUE, colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"), sep = ";", dec=".", na.strings="?")
power<-subset(power,power$Date == "1/2/2007" | power$Date == "2/2/2007")
power<-cbind(DateTime=as.POSIXct(paste(power$Date, power$Time), format="%d/%m/%Y %H:%M:%S"),power)
png("plot3.png")
plot(power$DateTime,power$Sub_metering_1,type="l", main="", xlab="", ylab="Energy sub metering")
lines(power$DateTime,power$Sub_metering_2,type="l", col="tomato2")
lines(power$DateTime,power$Sub_metering_3,type="l", col="blue")
legend('topright', legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty="solid",col=c("black","tomato2","blue"))
dev.off()